services:
  traefik:
    image: traefik:v3.6.2
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8000:80"
      - "8001:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  spark-master:
    container_name: spark-master
    build: .
    image: spark-image
    entrypoint: ['./entrypoint.sh', 'master']
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./data:/opt/spark/data
      - ./spark-logs:/opt/spark/spark-events
    env_file:
      - spark.env
      - model.env
    ports:
      - '8080:8080' # Spark master Web UI
      - '7077:7077' # For spark-node-to-spark-node queries
      - '4040:4040' # Spark worker data

  spark-history-server:
    container_name: spark-history
    image: spark-image
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-master
    env_file:
      - spark.env
    volumes:
      - ./data:/opt/spark/data
      - ./spark-logs:/opt/spark/spark-events
    ports:
      - '18080:18080'

  model-api:
    image: spark-image
    deploy:
      replicas: 2
    entrypoint: ['./entrypoint.sh', 'inference']
    env_file:
      - spark.env
      - model.env
    volumes:
      - ./data:/opt/spark/data
      - ./spark-logs:/opt/spark/spark-events
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.model-api.rule=PathPrefix(`/`)"
      - "traefik.http.services.model-api.loadbalancer.server.port=8000"

  spark-worker:
    container_name: spark-worker
    image: spark-image
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-master
    env_file:
      - spark.env
      - model.env
    volumes:
      - ./data:/opt/spark/data
      - ./spark-logs:/opt/spark/spark-events
    ports:
      - '8081:8081' # Spark worker Web UI

volumes:
  spark-logs:
