services:
  nginx:
    image: nginx:alpine
    container_name: inference
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - model-api
    networks:
      - music-match

  spark-master:
    container_name: spark-master
    build: .
    image: spark-image
    entrypoint: ['./entrypoint.sh', 'master']
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./data:/opt/spark/data
      - ./spark-logs:/opt/spark/spark-events
    env_file:
      - spark.env
      - model.env
    ports:
      - '8083:8080' # Spark master Web UI
      - '7077:7077' # For spark-node-to-spark-node queries
      - '4040:4040' # Spark worker data
    networks:
      - music-match

  spark-history-server:
    container_name: spark-history
    image: spark-image
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-master
    env_file:
      - spark.env
    volumes:
      - ./data:/opt/spark/data
      - ./spark-logs:/opt/spark/spark-events
    ports:
      - '18080:18080'
    networks:
      - music-match

  model-api:
    image: spark-image
    deploy:
      replicas: 2
    entrypoint: ['./entrypoint.sh', 'inference']
    env_file:
      - spark.env
      - model.env
    volumes:
      - ./data:/opt/spark/data
      - ./spark-logs:/opt/spark/spark-events
    networks:
      - music-match
  

  spark-worker:
    container_name: spark-worker
    image: spark-image
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-master
    env_file:
      - spark.env
      - model.env
    volumes:
      - ./data:/opt/spark/data
      - ./spark-logs:/opt/spark/spark-events
    ports:
      - '8084:8081' # Spark worker Web UI
    networks:
      - music-match

volumes:
  spark-logs:

networks:
  music-match:
    driver: bridge
